# config/meta.yml

meta_product_name: "nutri"
meta_title: "nutri - Improve your nutrition!"
meta_description: "A web application that allows nutritionists to create value for potential clients and expand their personal brand by curating lists of meals that can best serve specific target groups."
meta_image: "https://images.unsplash.com/photo-1466637574441-749b8f19452f?ixlib=rb-0.3.5&ixid=eyJhcHBfaWQiOjEyMDd9&s=1d992c355cbbe3f02ddc5f762f2ada73&auto=format&fit=crop&w=1000&q=80"                       # should exist in `app/assets/images/`
